### PR TITLE
Announcments for Hadoop recipes 

### PR DESCRIPTION
**Pull request by brandonbell**
Hi. 

I've added in announcements for Hadoop components (JT, NN, SNN, DT, TT).  

Also updated some of the port naming to be less ambiguous per the guidelines. 

Thanks,
Brandon

### CODE REVIEW

**Comment by brandonbell** [comment]
Added in HBase announcements and made minor changes to meet style guidelines.

**Comment by temujin9** [comment]
@brandonbell Could you bump minor versions, rather than just patch, for both of these? The attributes interface has changed for both, and while that probably doesn't warrant a full major bump, it's definitely too big a jump for a patch.

@mrflip - Can you weigh in with a +1 and/or any comments you have on these? I like what I see, but you're more familiar with Hadoop/HBase than I am.

**Comment by brandonbell** [comment]
@temujin9 - Thanks.  I upped minor version and will do that going forward for these type of changes.

**Comment by mrflip** [comment]
+1

**Comment by temujin9** [comment]
@brandonbell - Thank you.

I found I had to choose an earlier canonical string in the announcements for the components, due to a shortcoming in Zabbix that can't read past a certain point in the process string. Would you mind pulling the latest, and making sure it still works right with iron_cuke?

**Pull request merged**
