### PR TITLE
Reworked MongoDB 

### PR DESCRIPTION
**Pull request by brandonbell**
Hi. 

This is the reworked MongoDB Cookbook following style guidelines. 

Also, I added announcements to Zookeeper for log, deamon, and client / JMX ports.   

Let me know if there is some discrepancy with the style guidelines.  

Thanks,
Brandon

### CODE REVIEW

**Comment by brandonbell** [comment]
Added Zookeeper announcements for ports / daemons.

**Comment by temujin9** [comment]
One minor-ish quibble: we should not be going backwards on versions. Please update to a valid version (see http://semver.org/ for our preferred system).

Otherwise, looks good, and boots without error in the test-bed.

@mrflip - Could you take a quick pass at this, and make sure there aren't important Ironfantasticisms that I'm missing? I'm ready to pull once I get a thumbs-up from you (and a corrected version from Brandon).

**Comment by brandonbell** [comment]
Thanks - Little dyslexia or something.  

I incremented patch number on both MongoDB and Zookeeper . Let me know if it should be minor release.

**Comment by temujin9** [comment]
Where there's a deep change in underlying code, a minor release is called for. Not sure if that's true of ZK (make the call as you see fit), but it looks to be true of Mongo.

**Comment by brandonbell** [comment]
Understood and fixed.  

Thanks!

**Comment by temujin9** [comment]
Okay, looks (and works) good enough for me to pull in. @mrflip is on a plane to a conference, but when he gets the chance it'd be good to hear his input.

**Pull request merged**
