### PR TITLE
route53: Use data bag for aws keys

### PR DESCRIPTION
**Pull request by ryansch**
Store the aws credentials in a data bag.

### CODE REVIEW

**Comment by temujin9** [comment]
Unfortunately, this would pull this one cookbook out of line with the way we currently store and load AWS credentials for everything. I can't accept it into mainline.

We are considering several alternatives for how to store data like this. I suspect data bags may be the choice, but it'll take a lot more planning to implement.

Sorry, and thanks.

**Comment by ryansch** [comment]
I'll continue to maintain this patch on top of master.  Do you have any plans to split the cookbooks into their own repositories a la opscode-cookbooks?  I'm using them that way via git-subtree.

This is the actual source of my pull request: https://github.com/ace-cookbooks/route53

**Comment by temujin9** [comment]
We tried it, and found it to provide a fairly strong drag on development (and cause some pretty hideous network graphs, to boot). 

It may be that we didn't adequately plan our usage of it, or missed something that simplifies things. Is it just you pushing in changes on one end, or are you having many developers pushing (sometimes on either side of the subtree divide)? We found the latter situation caused much of the confusion, and lack of a good sync schedule did the rest.

**Comment by temujin9** [comment]
Re: maintaining the patch: I think you just killed the last two buggy bits I cared about for route53, so it's not likely to shift further anytime soon.

**Pull request closed without merging**
