### PR TITLE
Zookeeper

### PR DESCRIPTION
**Pull request by maplebed**
This pull request addresses two issues:
- the metachef and silverware cookbooks both have a STANDARD_DIRS defined.  The silverware definition overrides the metachef def, but has :root instead of 'root' as the user for a number of directories.  The :root symbol isn't defined anywhere.  I changed silverware to match metachef, using 'root' instead for the user.
- the zookeeper cookbook doesn't define default attributes for data_dir and journal_dir.  This causes some strange behavior that I don't fully understand - the homedir for the zookeeper user is initially set to one thing, then in the next chef run, chef tries to change it to /mnt/somethingerother.  (sorry, I don't remember the values.)  This homedir change fails because the zookeeper process is already running.  Adding default values for those two variables results in the homedir for the user being set correctly the first time.

### CODE REVIEW

**Comment by temujin9** [comment]
The metachef cookbook is a predecessor to silverware. Remove it from your chef server (`knife cookbook delete metachef -a -y`), and the commit changing things related to it ( a6deb43 ). The other commit looks good.

**Comment by temujin9** [comment]
(I've added a conflicts statement in silverware to catch this kind of error in future. Sorry it bit you, and thanks for the heads up.)

**Comment by temujin9** [comment]
Hrm. Examining the remaining one, I think I see an unfortunate collision of design choices. I'll have to discuss this further with the author of one of the conflicting choices, to get a feel for downstream implications.

**Comment by mrflip** [comment]
-1 on changing the symbols to strings in standard_dirs. The item is to_s'd when it later becomes the name of a user, but here it represents a directive, "make this be the name of superuser". In particular, BSD systems use 'wheel' not 'root' as their group. I suppose https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/silverware/definitions/standard_dirs.rb#L45 could benefit from a comment on same

I think your direct issue is that Zookeeper shouldn't be using `data_dir` as its home directory. https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/zookeeper/recipes/default.rb#L30

A default value will be trouble. The line should be there but the value should be nil, not `/var/lib/...`.

The choices here were made around the following things learned:
- you should be able to say nothing, in which case the directory is configured as the machine dictates
- you should be able to specify a value, in which case it is honored even if it differs from the default that volume_dirs would calculate
- intent should be clear: either a) say nothing and you get the machine's opinion, or b) specify a value and get that value
- a directory, once set, must not change.

---

Servers that take volume_dirs leave the whole decision about placement up to the volume_dirs helper. The way the logic works now is:
- if no value is set, the machine figures out a value and `.set`s it on the node
- if a value is set, the machine uses it.

It's not reasonable to start fine-slicing intent (was this value set as a cookbook default? was it set as a role default? etc) -- either you have an opinion (great, set the value) or you do not (great, we will use the _machine_'s opinion).

The reason for setting it on the node is that in the main case it would be catastrophic if the directory changed underneath an instance that has already joined a cluster: you'd have a situation where a full data segment is in directory A and the database starts up told to look in directory B. If you are intentionally moving a data directory, then you should also intentionally fix or reset the node attribute.

**Comment by temujin9** [comment]
I reluctantly agree with @mrflip - while I dislike configuration "sticking" in semi-hidden places, I suspect the consequences of it floating too much are more catastrophic. If you don't want to use the `volumes_dir` mechanism, you should probably be setting those target directories in a role, instead.

**Comment by maplebed** [comment]
I'm still not sure how to get out of my problem at the moment, where on node creation, the zookeeper user is created with a homedir of /var/run/zookeeper, but then on the second chef run it's changed to /mnt/zookeeper/data.

My wrapper cookbook is including the recipe zookeeper::server, so that' the starting point in the cookbook.  <a href="https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/zookeeper/recipes/server.rb#L24">Line 24</a> pulls in the default recipe, which on <a href="https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/zookeeper/recipes/default.rb#L29">line 29</a> attempts to create the user, passing in the (as yet unset) node[:zookeeper][:data_dir] attribute.  Because the <a href="https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/silverware/definitions/daemon_user.rb">daemon_user</a> definition has no value for :home, it chooses /var/run/zookeper.  

Once the zookeeper::default recipe finishes and execution returns to the server recipe, <a href="https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/zookeeper/recipes/server.rb#L29">it sets</a> the value of data_dir to (in my case) /mnt/zookeeper/data.  This attribute is not used on the current run, since the user has already been created, however, it is present on the following run, at which point the daemon_user definition attempts to change the homedir from /var/run/zookeeper to /mnt/zookeeper/data_dir.

Is the right solution to change zookeeper::default to use something other than the data_dir for the user's home?  In that case what should it use?  (in fact, simply removing <a href="https://github.com/infochimps-labs/ironfan-pantry/blob/master/cookbooks/zookeeper/recipes/default.rb#L30">line 30</a> does seem to make my problem go away, but I don't know what other ramifications it might have, as I don't yet have a working zookeeper environment running.  It doesn't strike me as wonderful though that the homedir doesn't exist...)

**Comment by temujin9** [comment]
We get out of it is by preconstructing the node with a `:volumes` attribute, in Ironfan's knife plugin. This means that the volumes cookbook has the right hash from the get-go.

You could achieve something similar using attributes set in roles. It's less dynamic (and you'll have to manually construct the expected hash), but it should be pretty straightforward.

**Pull request closed without merging**
